name: faustedition

services:
  web:
    image: faustedition/www:latest
    expose:
      - 80
    links:
      - exist
      - macrogen
    build:
      context: .
      target: www
  exist:
    image: faustedition/exist:latest
    expose:
      - 8080
    build:
      context: .
      target: exist
  macrogen:
    image: faustedition/macrogen:latest
    expose:
      - 5001
    build:
      context: .
      target: macrogen
