name: faustedition

services:
  web:
    image: thvitt/faustedition-www:latest
    ports:
      - "9000:80"
    links:
      - exist
      - macrogen
      - downloads
    volumes:
      - facsimile:/facsimile
    build:
      context: .
      target: www
  exist:
    image: thvitt/faustedition-exist:latest
    expose:
      - 8080
    build:
      context: .
      target: exist
  macrogen:
    image: thvitt/faustedition-macrogen:latest
    expose:
      - 5001
    build:
      context: .
      target: macrogen
  downloads:
    image: thvitt/faustedition-downloads:latest
    expose:
      - 5051
    volumes:
      - facsimile:/facsimile
    build:
      context: .
      target: downloadserver

  v1.0:
    image: thvitt/faustedition-www:1.0rc
    ports:
      - "9010:80"
    volumes:
      - facsimile:/facsimile

  v1.1:
    image: thvitt/faustedition-www:1.1rc
    ports:
      - "9011:80"
    volumes:
      - facsimile:/facsimile

  v1.2:
    image: thvitt/faustedition-www:1.2rc
    ports:
      - "9012:80"
    volumes:
      - facsimile:/facsimile

  v1.3:
    image: thvitt/faustedition-www:1.3rc
    ports:
      - "9013:80"
    volumes:
      - facsimile:/facsimile

volumes:
  facsimile:
    driver: local
    driver_opts:
      type: none
      device: /mnt/data/faust/facsimiles/transcript/facsimile
      o: bind
