name: faustedition

services:
  web:
    image: faustedition/www:latest
    expose:
      - 80
    build:
      context: .
      target: www
  exist:
    image: faustedition/exist:latest
    expose:
      - 8080
    build:
      context: .
      target: exist
