name: faustedition

services:
  web:
    image: faustedition/www:latest
    expose:
      - 80
    links:
      - exist
      - macrogen
      - downloads
    volumes:
      - facsimile:/facsimile
    build:
      context: .
      target: www
  exist:
    image: faustedition/exist:latest
    expose:
      - 8080
    build:
      context: .
      target: exist
  macrogen:
    image: faustedition/macrogen:latest
    expose:
      - 5001
    build:
      context: .
      target: macrogen
  downloads:
    image: faustedition/downloads:latest
    expose:
      - 5051
    volumes:
      - facsimile:/facsimile
    build:
      context: .
      target: downloadserver

volumes:
  facsimile:
    driver: local
    driver_opts:
      type: none
      device: /mnt/data/faust/facsimiles/transcript/facsimile
      o: bind
