# yaml-language-server: $schema=https://gist.githubusercontent.com/tcztzy/3e4b8c96b84d5fad992f38c893476baa/raw/1cfd2b4f8dbf907bb8819210814059422c8a0980/python.logging.schema.json

version: 1

formatters:
  detailed:
    format: "%(asctime)s:%(levelname)-8s:%(name)-8s:%(message)s"

handlers:
  stdout:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    level: INFO
    formatter: detailed
  stderr:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    level: WARNING
    formatter: detailed

root:
  handlers:
    - stdout
    - stderr
  level: INFO
